### ISSUE TITLE
recursive-restart-case → restart-labels ?

### ISSUE THREAD

**Issue by guicho271828** [heegaiximephoomeeghahyaiseekh/recursive-restart#2]
how about aliasing `recursive-restart-case` to `restart-labels` ? The nature of mutual recursion will be more obvious, and its a bit shorter.

**Comment by guicho271828** [comment]
well, their forms can be different. I made `restart-labels` look more like `labels`.    a9490a1

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
I just merged your pull request. Closing issue.
